export const FlexokiDark = {
  background: "#100F0F",
  foreground: "#CECDC3",
  card: "#282726",
  cardForeground: "#CECDC3",
  popover: "#282726",
  popoverForeground: "#CECDC3",
  primary: "#EC8B49",
  primaryHover: "#F9AE77",
  primaryForeground: "#FFFCF0",
  muted: "#1C1B1A",
  mutedForeground: "#878580",
  secondary: "#1C1B1A",
  secondaryForeground: "#CECDC3",
  accent: "#343331",
  accentForeground: "#CECDC3",
  destructive: "#D14D41",
  destructiveForeground: "#FFFCF0",
  success: "#A0AF54",
  successForeground: "#FFFCF0",
  info: "#4385BE",
  infoForeground: "#FFFCF0",
  warning: "#D0A215",
  warningForeground: "#100F0F",
  border: "#343331",
  input: "#1C1B1A",
  ring: "#EC8B49",
} as const;

export const FlexokiLight = {
  background: "#FFFCF0",
  foreground: "#100F0F",
  card: "#E6E4D9",
  cardForeground: "#100F0F",
  popover: "#E6E4D9",
  popoverForeground: "#100F0F",
  primary: "#DA702C",
  primaryHover: "#BC5215",
  primaryForeground: "#FFFCF0",
  muted: "#F2F0E5",
  mutedForeground: "#6F6E69",
  secondary: "#F2F0E5",
  secondaryForeground: "#100F0F",
  accent: "#E6E4D9",
  accentForeground: "#100F0F",
  destructive: "#AF3029",
  destructiveForeground: "#FFFCF0",
  success: "#66800B",
  successForeground: "#FFFCF0",
  info: "#205EA6",
  infoForeground: "#FFFCF0",
  warning: "#AD8301",
  warningForeground: "#100F0F",
  border: "#DAD8CE",
  input: "#F2F0E5",
  ring: "#DA702C",
} as const;

export type ThemeColors = typeof FlexokiDark | typeof FlexokiLight;

export function getThemeColors(isDark: boolean): ThemeColors {
  return isDark ? FlexokiDark : FlexokiLight;
}
