name: Feature request
description: Suggest an improvement or new capability
title: "feat: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What are you trying to do?
      placeholder: "As a user, I want..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
      placeholder: UI, behavior, config, etc.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Other approaches you've tried/considered"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, mockups, etc.
